### ISSUE TITLE
Allow customisation of NPM registry URL

### ISSUE THREAD

**Issue by tehsenaus** [NewSpring/ci-npm-publish#3]
It'd be nice to use your package with our internal NPM registry - could you add a command line parameter for the registry URL?

**Comment by jbaxleyiii** [comment]
@tehsenaus you bet! I'll let you know when its done!

**Comment by jbaxleyiii** [comment]
@tehsenaus you should be good to try pulling the registry branch and running it per the above PR. Let me know if you have any issues
